import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: "#050208",
          50: "#0a0515",
          100: "#0f0820",
          200: "#150d2e",
          300: "#1c1240",
          400: "#251a55",
        },
        cream: {
          DEFAULT: "#efe8d8",
          50: "#faf8f3",
          100: "#f5f0e8",
          200: "#efe8d8",
          300: "#e0d4bb",
          400: "#c9b999",
        },
        gold: {
          DEFAULT: "#c8956e",
          50: "#fdf6f0",
          100: "#f8e8d8",
          200: "#f0d0b0",
          300: "#e8b48a",
          400: "#c8956e",
          500: "#a87a58",
          600: "#8a6248",
        },
        violet: {
          DEFAULT: "#8b5cf6",
          50: "#f5f0ff",
          100: "#ede5ff",
          200: "#ddd0ff",
          300: "#c4acff",
          400: "#a78bfa",
          500: "#8b5cf6",
          600: "#7c3aed",
          700: "#6d28d9",
          800: "#5b21b6",
          900: "#4c1d95",
        },
        rose: {
          DEFAULT: "#ff6b9d",
          50: "#fff1f5",
          100: "#ffe0ea",
          200: "#ffc2d6",
          300: "#ff94b5",
          400: "#ff6b9d",
          500: "#f43f72",
          600: "#e11d5a",
          700: "#be123c",
        },
      },
      fontFamily: {
        sans: ["var(--font-dm-sans)", "system-ui", "-apple-system", "sans-serif"],
        display: ["var(--font-syne)", "system-ui", "-apple-system", "sans-serif"],
        serif: ["var(--font-playfair)", "Georgia", "serif"],
      },
      fontSize: {
        "xs": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.05em" }],
        "sm": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.025em" }],
        "base": ["1rem", { lineHeight: "1.6", letterSpacing: "0em" }],
        "lg": ["1.125rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em" }],
        "xl": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.015em" }],
        "2xl": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.02em" }],
        "3xl": ["2rem", { lineHeight: "2.25rem", letterSpacing: "-0.025em" }],
        "4xl": ["2.5rem", { lineHeight: "1.15", letterSpacing: "-0.03em" }],
        "5xl": ["3.25rem", { lineHeight: "1.1", letterSpacing: "-0.035em" }],
        "6xl": ["4rem", { lineHeight: "1.05", letterSpacing: "-0.04em" }],
        "7xl": ["5rem", { lineHeight: "1.05", letterSpacing: "-0.045em" }],
        "8xl": ["6.5rem", { lineHeight: "1", letterSpacing: "-0.05em" }],
        "9xl": ["8rem", { lineHeight: "0.95", letterSpacing: "-0.055em" }],
        "10xl": ["10rem", { lineHeight: "0.9", letterSpacing: "-0.06em" }],
      },
      borderRadius: {
        "4xl": "2rem",
        "5xl": "2.5rem",
      },
      animation: {
        "fade-in": "fadeIn 0.8s ease-out forwards",
        "slide-up": "slideUp 0.8s ease-out forwards",
        "marquee": "marquee 30s linear infinite",
        "marquee-reverse": "marquee-reverse 30s linear infinite",
        "grain": "grain 8s steps(10) infinite",
        "float": "float 6s ease-in-out infinite",
        "pulse-slow": "pulse 4s ease-in-out infinite",
        "spin-slow": "spin 20s linear infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(30px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "marquee-reverse": {
          "0%": { transform: "translateX(-50%)" },
          "100%": { transform: "translateX(0%)" },
        },
        grain: {
          "0%, 100%": { transform: "translate(0, 0)" },
          "10%": { transform: "translate(-5%, -10%)" },
          "20%": { transform: "translate(-15%, 5%)" },
          "30%": { transform: "translate(7%, -25%)" },
          "40%": { transform: "translate(-5%, 25%)" },
          "50%": { transform: "translate(-15%, 10%)" },
          "60%": { transform: "translate(15%, 0%)" },
          "70%": { transform: "translate(0%, 15%)" },
          "80%": { transform: "translate(3%, 35%)" },
          "90%": { transform: "translate(-10%, 10%)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-15px)" },
        },
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-mesh": "linear-gradient(135deg, var(--tw-gradient-from), var(--tw-gradient-via), var(--tw-gradient-to))",
      },
    },
  },
  plugins: [],
};
export default config;
